# Generated by Django 2.2 on 2019-05-20 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=5)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('noteType', models.CharField(blank=True, max_length=10)),
                ('noteContent', models.CharField(default='[]', max_length=9223372036854775807)),
                ('noteSkeleton', models.CharField(default='[]', max_length=9223372036854775807)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.User')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.Note')),
            ],
        ),
    ]
