# Generated by Django 2.2 on 2019-05-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
    ]
