# Generated by Django 2.2 on 2019-05-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20190526_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='MyFile',
        ),
    ]
